### ISSUE TITLE
OGP BuilderのuploadがProtected Branchesによりブロックされる

### ISSUE THREAD

**Issue by come25136** [stopcovid19-okayama/covid19#117]
## 起こっている問題 / The Problem
- masterへ半自動更新する際のマージでOGP Builderのuploadが失敗する
- https://github.com/stopcovid19-okayama/covid19/runs/582608209#step:5:7
## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/12409412/79197344-861f7e00-7e6c-11ea-8dd1-afdcef348c0e.png)

## 期待する見せ方・挙動 / Expected Behavior
- Actionがエラーで止まらずに完走する

## 起こっている問題の再現手段 / Steps to Reproduce
1. 21:00に自動生成されるPR(master-xxx)をマージする

## 動作環境・ブラウザ / Environment
- GitHub Actions

**Comment by fujiwaraizuho** [comment]
対応しました〜

**Comment by come25136** [comment]
まだ失敗しているのでリスポーン

**Comment by fujiwaraizuho** [comment]
@y-chan 
これについてなにか知見あったら教えてください

**Comment by y-chan** [comment]
私Branch Protectionの問題はあまり経験がないので分からない...

**Comment by y-chan** [comment]
兵庫版ではここで言うところのproductionに直接ogpを投げてBranch Productionを回避している感じだったと思う

**Comment by nomunomu0504** [comment]
プロテクション回避して、ブランチにマージしたいってことですか？👀

**Comment by Nekoya3** [comment]
Restrict who can push to matching branches
をmasterにprotectionとして付与しているのであればそこにActions追加してあげればいい？だめ？ですかね

**Comment by nomunomu0504** [comment]
福井県版では `auto-merge` っていうアプリ使って自動でマージしてますね。

**Comment by Nekoya3** [comment]
正攻法それですよね…
（北海道は別リポジトリで処理しちゃってます

**Comment by y-chan** [comment]
色々兵庫版でも試したんですが、pushには使えないという結論に至った...

**Comment by nomunomu0504** [comment]
うーん。正攻法で攻めるのが一番手取り早いような気が...。

悩んでる時間がもったいなくて、我々はそうしてしまいましたが。

**Comment by Nekoya3** [comment]
起こっている問題の再現手段 / Steps to Reproduce
21:00に自動生成されるPR(master-xxx)のaction実行を待つ

なのもおかしいような....なぜPRで実行しているactionなのにmasterに対してpushしているのでしょう...?
HEAD -> masterなのでpushの向き先を自動生成されているブランチに向ければいいと思うのですが...

**Comment by fujiwaraizuho** [comment]
確かに…
とりあえず正攻法で行きましょうか
現状、差分を直接pushしているものをPR発行に置き換えてpr-labelerを使ってPRにラベルをつけてAuto mergeさせましょう

**Comment by y-chan** [comment]
pr labeler使わなくてもprのactionにlabesl: auto_marge とかで行けますね。
https://github.com/stop-covid19-hyogo/covid19/blob/development/.github/workflows/i18n_builder.yml#L36

**Comment by fujiwaraizuho** [comment]
おっ、なるほど！！！

**Comment by fujiwaraizuho** [comment]
auto_mergeを行うためにはauto_merge_botの導入が必要みたいなので、とりあえずインストールしておきました！
![Screenshot from 2020-04-26 22-57-48](https://user-images.githubusercontent.com/30709744/80309747-cdfdb800-8811-11ea-985b-d615e1e187e7.png)
