### ISSUE TITLE
検査陽性者の状況カードが個別に表示できていない

### ISSUE THREAD

**Issue by y-chan** [stopcovid19-okayama/covid19#125]
## 起こっている問題 / The Problem
- 表題の通り

## 期待する見せ方・挙動 / Expected Behavior
- 個別に表示できるようにする

## 起こっている問題の再現手段 / Steps to Reproduce
1. https://okayama.stopcovid19.jp/cards/details-of-confirmed-cases にアクセスする

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by fujiwaraizuho** [comment]
oh......忘れてた
ありがとう！

**Comment by y-chan** [comment]
対応しておくよ

**Comment by fujiwaraizuho** [comment]
大好き
