### ISSUE TITLE
クリエイティブ・コモンズ表示を追加

### ISSUE THREAD

**Issue by fujiwaraizuho** [stopcovid19-okayama/covid19#128]
## 改善詳細 / Details of Improvement
- クリエイティブ・コモンズ表示を追加

## スクリーンショット / Screenshot

![5BF62E43-EED1-4224-B902-3D6383DCECE6](https://user-images.githubusercontent.com/30709744/79439400-be12f680-800f-11ea-8b62-148e7f5a0684.jpeg)

**Comment by aptus-jp** [comment]
やります！

**Comment by fujiwaraizuho** [comment]
よろしくお願いします！

**Comment by aptus-jp** [comment]
CC-BY 4.0でいいですね？

**Comment by fujiwaraizuho** [comment]
はい、問題ないです！

**Comment by fujiwaraizuho** [comment]
prettierのバージョンがあがっていて後のテストに影響が出ていたのでPRをRevertしました。
再実装をお願いいたします

**Comment by aptus-jp** [comment]
おっと，すみません
対応します

**Comment by aptus-jp** [comment]
実装し直したのでReviewお願いします
