### ISSUE TITLE
オープンデータを入手 リンクをすべてのカードに追加

### ISSUE THREAD

**Issue by fujiwaraizuho** [stopcovid19-okayama/covid19#129]
## 改善詳細 / Details of Improvement
- オープンデータを入手 リンクをすべてのカードに追加

## スクリーンショット / Screenshot

![BB42841B-79F0-4639-98AE-11FCBAE80F9F](https://user-images.githubusercontent.com/30709744/79439976-6fb22780-8010-11ea-8277-fef87118bd61.jpeg)

**Comment by furandon-pig** [comment]
このタスクに着手してみます。

**Comment by furandon-pig** [comment]
オープンデータへのリンクがついているカードは、すべて以下のURLとなっておりますので、本タスクで追加するリンクも同じURLを設定しようと思います。

```
http://www.okayama-opendata.jp/opendata/ga120PreAction.action?keyTitle=d9c4776db7f09fff161953a2aaf03b80a9abad48&datasetId=e6b3c1d2-2f1f-4735-b36e-e45d36d94761
```

■補足：
[stopcovid19-okayama/covid19-scraping](https://github.com/stopcovid19-okayama/covid19-scraping)のスクリプトでは、「検査陽性者の状況」等は複数のURLから取得した値からJSONを生成しています(例：[main_summary()](https://github.com/stopcovid19-okayama/covid19-scraping/blob/master/convert.php#L247))。ただ、カードのVueファイル([components/cards/TestedNumberCard.vue](https://github.com/stopcovid19-okayama/covid19/blob/development/components/cards/TestedNumberCard.vue#L10))では、オープンデータへのURLはひとつしか指定できないようです。

**Comment by fujiwaraizuho** [comment]
ありがとうございます！
全ておなじURLで進めていただいて問題ありません。

**Comment by furandon-pig** [comment]
すみません、実装方針について一点相談させてください。
「陽性患者の属性」と「陽性患者数」にはオープンデータへのリンクを追加できたのですが、「検査陽性者の状況」は[東京版](https://stopcovid19.metro.tokyo.lg.jp/)にもまだリンクが実装されていないようです。

 * [岡山県 新型コロナウイルス感染症対策サイト (非公式)](https://okayama.stopcovid19.jp/)
 * [東京都 新型コロナウイルス感染症対策サイト](https://stopcovid19.metro.tokyo.lg.jp/)

「検査陽性者の状況」は現状のまま(リンクを追加しない)とし、現状リンクを追加できた内容で一旦プルリクをお出しするという方針でもよろしいでしょうか？
(ここで「検査陽性者の状況」に独自にリンクを追加しても、逆に東京版のマージで手間がでると思いますので...)

**Comment by fujiwaraizuho** [comment]
その方針で問題ありません！
