### ISSUE TITLE
nuxt.config.tsのマージミス

### ISSUE THREAD

**Issue by y-chan** [stopcovid19-okayama/covid19#132]
## 起こっている問題 / The Problem
- 前回の東京都版マージで、既にlayouts/default.vueに移行済みの部分が1部nuxt.config.ts内に残っている。

## 期待する見せ方・挙動 / Expected Behavior
- 不要な部分を消し、layouts/default.vueに移行し切る

**Comment by y-chan** [comment]
ごめんなさい、これ見間違えかもしれない

**Comment by y-chan** [comment]
気のせいではなかったのでReopen

**Comment by fujiwaraizuho** [comment]
これどこの部分だろう

**Comment by y-chan** [comment]
だいたいここ
https://github.com/stopcovid19-okayama/covid19/blob/development/nuxt.config.ts#L22-L49

軽く見て不自然に思ったところなので、詳しくは差分見ないと何とも

**Comment by fujiwaraizuho** [comment]
なるほど、東京都版の最新を引っ張ってくる時に一緒に直しちゃうわ

**Comment by y-chan** [comment]
https://github.com/stopcovid19-okayama/covid19/commit/7cb1e09ecfde2fa4bd439d862f01d769afdf3a9f#diff-a216f5c067bcf89f670f6d5d950695b8
このコミットっぽい

**Comment by fujiwaraizuho** [comment]
助かる、ありがとう👍👍
