### ISSUE TITLE
埋め込み（iframe）がうまく動作しない

### ISSUE THREAD

**Issue by aptus-jp** [stopcovid19-okayama/covid19#142]
## 起こっている問題 / The Problem
- カードのiframe埋め込みコードを、埋め込んでもグレーアウトで止まっている

## スクリーンショット / Screenshot
<img width="1061" alt="スクリーンショット 2020-04-18 0 02 52" src="https://user-images.githubusercontent.com/49401718/79583337-f3027480-8107-11ea-9f23-4656f0bb4777.png">

## 期待する見せ方・挙動 / Expected Behavior
- 正常にカードの内容（ここでは一番左上の「検査陽性者の状況」）が表示される

## 起こっている問題の再現手段 / Steps to Reproduce
0. Railsアプリ→ビューを作る
1. iframeタグ取得
2. 貼り付ける

## 動作環境・ブラウザ / Environment
- macOS
- Chrome・Opera

**Comment by nomunomu0504** [comment]
対策サイトの方で、カードのみの表示をした場合に、グラフって正常に表示されてます？🤔

**Comment by aptus-jp** [comment]
「検査陽性者の状況」だけ動作していないようです...
