### ISSUE TITLE
DataView内のShare Buttonが正しく動作しない

### ISSUE THREAD

**Issue by Nekoya3** [stopcovid19-okayama/covid19#168]
## 起こっている問題 / The Problem
- OGP Imageが真っ白
- タイトルが東京都のものになっている

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/17000370/80202069-06f62b00-8660-11ea-8c25-6aa67ad0682d.png)

## 期待する見せ方・挙動 / Expected Behavior
- OGP Imageがグラフカードのスクリーンショット画像になる、もしくは通常OGP Imageが表示される。
- Twitterへの共有用リンクの文字列を岡山県のものに変更する。

**Comment by come25136** [comment]
タイトルについては #165 にて修正済みです

**Comment by fujiwaraizuho** [comment]
OGP画像については #117 が関係してそうですね

**Comment by Nekoya3** [comment]
@come25136 ということはリリースに上がってないだけなんですね、了解です
