### ISSUE TITLE
陽性患者の属性カードから退院カラムを消す

### ISSUE THREAD

**Issue by come25136** [stopcovid19-okayama/covid19#174]
## 改善詳細 / Details of Improvement
- タイトル通り

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/12409412/80269886-9a763d00-86ee-11ea-8e4d-2338ae1190d1.png)

## 期待する見せ方・挙動 / Expected behavior
- 退院カラムが無い状態にする

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by furandon-pig** [comment]
本件、着手しようと思います。

**Comment by furandon-pig** [comment]
「陽性患者の属性」カードの退院カラムは、「退院」データが現状存在しない(or提供されていない?)ため、空になるので消しておきたいという背景であると認識しています。
修正方針としては、後々退院データが提供されることを想定し、不要部分のコメントアウトにより表示させなくするという形で対応しようと考えています。
