### ISSUE TITLE
新型コロナウイルス感染症予防フライヤーのダウンロードページ作成

### ISSUE THREAD

**Issue by manate-anagram** [stopcovid19-okayama/covid19#1807]
## 改善詳細 / Details of Improvement
- フライヤーのダウンロードページ作成
- スクリーンショットでサイトロゴが入っている部分にフライヤー画像
- ライセンスの表記はCCBY0の画像(CSSのimage指定でダウンロード不可)
- formはGoogle Form
- スクリーンショットの協力団体・企業の欄はテキストのみ

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/34095156/99935559-4e829800-2da4-11eb-8b93-ec589758d457.png)

**Comment by fujiwaraizuho** [comment]
こちら一旦close します。
