### ISSUE TITLE
「岡山緊急事態宣言について」のURLが存在しない

### ISSUE THREAD

**Issue by gorira-tatsu** [stopcovid19-okayama/covid19#190]
## 起こっている問題 / The Problem
- 現在「岡山緊急事態宣言について」をクリックすると「お探しのページを見つけることはできませんでした」と表示されページが存在しない。

## スクリーンショット / Screenshot
<img width="1160" alt="スクリーンショット 2020-04-30 16 27 43" src="https://user-images.githubusercontent.com/59169390/80683753-a3f11200-8aff-11ea-904f-b50941c155d5.png">
<img width="1406" alt="スクリーンショット 2020-04-30 16 28 00" src="https://user-images.githubusercontent.com/59169390/80683758-a5bad580-8aff-11ea-96da-dd211380d2e9.png">

## 期待する見せ方・挙動 / Expected Behavior
- 利用者が混乱しないためにもその表示を消すか、別の存在するページを反映する必要がある。

## 動作環境・ブラウザ / Environment
- macOS
- Firefox

**Comment by fujiwaraizuho** [comment]
代わりにこちらのURLに差し替えましょう
https://youtu.be/mUwVyGTMWn8

**Comment by gorira-tatsu** [comment]
了解です。ちょっとやってみます。
