### ISSUE TITLE
design: 「医療非常事態宣言発令中」がホバーすると文字が見えなくなる

### ISSUE THREAD

**Issue by kazuemon** [stopcovid19-okayama/covid19#2133]
## 起こっている問題 / The Problem
- ホバーすると背景と文字の色が同じになって文字が読めなくなる
※入力中に送信されてしまって、最初変な状態でissue投げてしまいすみません

## スクリーンショット / Screenshot
- ホバー前
![image](https://user-images.githubusercontent.com/12812934/103074399-d7dbf300-460c-11eb-9a7a-5baa7428ac0d.png)
- ホバー後
![image](https://user-images.githubusercontent.com/12812934/103074408-de6a6a80-460c-11eb-9c47-f3a0ed5322cc.png)

## 期待する見せ方・挙動 / Expected Behavior
- フォーカスして見た目が変わるのが正しいかどうかわかりませんが一応これが期待の挙動でしょうか？
![image](https://user-images.githubusercontent.com/12812934/103074571-3d2fe400-460d-11eb-9bea-751b3bb126e0.png)

```css
.linkButton_2jzn_:hover {
    background-color: #fff;
    color: #ad2121;
}
```

## 起こっている問題の再現手段 / Steps to Reproduce
トップページ `.TokyoAlert-link .linkButton_2jzn_` にマウスカーソルを合わせる

## 動作環境・ブラウザ / Environment
- Chrome

**Comment by fujiwaraizuho** [comment]
おおお…ありがとうございます！
