### ISSUE TITLE
PCR検査相談の要件変更に伴うフローチャートの変更

### ISSUE THREAD

**Issue by mizphses** [stopcovid19-okayama/covid19#215]
## 起こっている問題 / The Problem
- PCR検査相談の要件から体温の基準がなくなったことを受け，表記を変更したい。

## 期待する見せ方・挙動 / Expected Behavior
- https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/kenkou_iryou/dengue_fever_qa_00001.html#Q5-1 に基づく表記にする

**Comment by come25136** [comment]
本件は全国的な見直しのため、本家のissueに作るのが適切だと思います

**Comment by y-chan** [comment]
本家のフローは既に書き換えられていて、こことは全く別になっているので、今のところはこちらでよいと思います。

**Comment by mizphses** [comment]
書き換え版出しました
