### ISSUE TITLE
OGP画像が東京都版のままになっている

### ISSUE THREAD

**Issue by fujiwaraizuho** [stopcovid19-okayama/covid19#22]
## 起こっている問題 / The Problem
- OGP画像が東京都版のままになっている

## スクリーンショット / Screenshot
![Screenshot from 2020-03-30 16-41-53](https://user-images.githubusercontent.com/30709744/77887458-91d44780-72a5-11ea-8dfd-006b661a9194.png)

## 期待する見せ方・挙動 / Expected Behavior
- OGP画像を岡山県版のものに変更する

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by Lusaca** [comment]
もともと、岡山用のOGP画像だったが念の為変更した。

**Comment by fujiwaraizuho** [comment]
Thanks!
次から、なるべく直コミットは避けてほしい
PR発行していく感じで！

**Comment by fujiwaraizuho** [comment]
ん、ちょっとまてよ
productionのogp.pngも正しいのにOGP画像が変わらないのはなぜだ？

**Comment by Lusaca** [comment]
Twitterが前のOGP画像をキャッシュしている可能性？

**Comment by fujiwaraizuho** [comment]
いや、これ多分東京都から差分引っ張ってきたのが原因だ
nuxt.config.ts だけ変えても変わらなくなってる
https://github.com/stop-covid19-kyoto/covid19-kyoto/commit/020e8d9e662c98883c100ceaab24b3004dfeb36e
