### ISSUE TITLE
検査陽性者の状況に入院予定枠を増やす

### ISSUE THREAD

**Issue by come25136** [stopcovid19-okayama/covid19#220]
## 改善詳細 / Details of Improvement
- 検査陽性者の状況に入院予定枠を増やす

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/12409412/81500907-12a84980-9310-11ea-8c3f-2fb34f4d9890.png)

## 期待する見せ方・挙動 / Expected behavior
- スクリーンショット参照

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by fujiwaraizuho** [comment]
やります！
