### ISSUE TITLE
「陽性者の属性」の「オープンデータを入手」のリンクが切れている

### ISSUE THREAD

**Issue by come25136** [stopcovid19-okayama/covid19#2282]
## 起こっている問題 / The Problem
- `陽性者の属性`の`オープンデータを入手`のリンクが切れている

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/12409412/103716071-7ef55d00-5005-11eb-818d-9bb5c33c3d18.png)

## 期待する見せ方・挙動 / Expected Behavior
- [感染者詳細情報](http://www.okayama-opendata.jp/opendata/ga130PreAction.action?resourceName=%E6%84%9F%E6%9F%93%E8%80%85%E8%A9%B3%E7%B4%B0%E6%83%85%E5%A0%B1&keyTitle=d9c4776db7f09fff161953a2aaf03b80a9abad48&title=%E6%96%B0%E5%9E%8B%E3%82%B3%E3%83%AD%E3%83%8A%E3%82%A6%E3%82%A4%E3%83%AB%E3%82%B9%E6%84%9F%E6%9F%93%E7%97%87%E3%81%AB%E9%96%A2%E3%81%99%E3%82%8B%E3%83%87%E3%83%BC%E3%82%BF%EF%BC%88%E5%B2%A1%E5%B1%B1%E7%9C%8C%EF%BC%89&isParam=1&resourceId=d021c012-297e-4ea9-bffa-cf55741884d1&licenseTitle=%E3%82%AF%E3%83%AA%E3%82%A8%E3%82%A4%E3%83%86%E3%82%A3%E3%83%96%E3%83%BB%E3%82%B3%E3%83%A2%E3%83%B3%E3%82%BA+%E8%A1%A8%E7%A4%BA&datasetId=e6b3c1d2-2f1f-4735-b36e-e45d36d94761&checkFieldFormat=CSV)にリンク

## 起こっている問題の再現手段 / Steps to Reproduce
1. https://okayama.stopcovid19.jp/ 行って`陽性者の属性`の`オープンデータを入手`をクリック

## 動作環境・ブラウザ / Environment
- macOS Catalina 10.15.7
- Chrome 87.0.4280.88（Official Build） （x86_64）

**Comment by fujiwaraizuho** [comment]
対応します！
