### ISSUE TITLE
OGP全体の修正ミス

### ISSUE THREAD

**Issue by y-chan** [stopcovid19-okayama/covid19#23]
## 関連issue
#22 

## 起こっている問題 / The Problem
- OGP画像に限らず説明書きも東京のものになっている

**Comment by y-chan** [comment]
@fujiwaraizuho 
「東京都が開設した～」の流れは「(県内の)学生エンジニアが開設した～」に統一するけどおｋ？
私県民じゃないからあれだけど
指定あったらよろしく

**Comment by fujiwaraizuho** [comment]
学生エンジニアの表記は該当部分全部消そう
OSSにして学生以外も参加してくださるだろうし

「有志が開設した～」でどうだろう

**Comment by y-chan** [comment]
おｋ、それで統一する
