### ISSUE TITLE
当サイトについての学生エンジニア一覧を削除

### ISSUE THREAD

**Issue by fujiwaraizuho** [stopcovid19-okayama/covid19#28]
## 起こっている問題 / The Problem
- 学生エンジニアがハードコーディングされている

## 期待する見せ方・挙動 / Expected Behavior
- 貢献者が増えることを考慮して [CONTRIBUTORS.md](https://github.com/stopcovid19-okayama/covid19/blob/development/CONTRIBUTORS.md) へのリンクを張る

**Comment by laminne** [comment]
対応します
