### ISSUE TITLE
”新型コロナウイルス感染症が心配なときに” へのBOXを復活させる

### ISSUE THREAD

**Issue by fujiwaraizuho** [stopcovid19-okayama/covid19#29]
## 改善詳細 / Details of Improvement
- ”新型コロナウイルス感染症が心配なときに” へのBOXを復活させる

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/30709744/77913684-a9282a80-72cf-11ea-8def-979d55065b86.png)

**Comment by manate-anagram** [comment]
@fujiwaraizuho 対応します！

**Comment by fujiwaraizuho** [comment]
よろしくお願いします！
