### ISSUE TITLE
雇用調整助成金の相談窓口について (岡山労働局) のリンク切れ

### ISSUE THREAD

**Issue by fujiwaraizuho** [stopcovid19-okayama/covid19#30]
## 起こっている問題 / The Problem
- 企業の皆様・はたらく皆様へにある "雇用調整助成金の相談窓口について (岡山労働局)" のリンクが切れている

## 期待する見せ方・挙動 / Expected Behavior
- リンクを[新しいもの](https://jsite.mhlw.go.jp/okayama-roudoukyoku/hourei_seido_tetsuzuki/kakushu_joseikin/tetsuzuki/_120417_00004.html)へ差し替える

**Comment by manate-anagram** [comment]
@fujiwaraizuho 対応します

**Comment by fujiwaraizuho** [comment]
よろしくお願いします！
