### ISSUE TITLE
GitHub ActionのステータスをSlackに送信する

### ISSUE THREAD

**Issue by fujiwaraizuho** [stopcovid19-okayama/covid19#32]
## 改善詳細 / Details of Improvement
- [これ](https://github.com/marketplace/actions/action-slack)を使ってSlackにGitHub Actionのステータスを送信する

**Comment by laminne** [comment]
4/1に挑戦してみます

**Comment by fujiwaraizuho** [comment]
SLACK_WEBHOOK_URLとGITHUB_TOKENに関してはSecretsに登録してあるので変数から利用できます！

**Comment by fujiwaraizuho** [comment]
@laminne 出来そう…？

**Comment by laminne** [comment]
まだ手をつけられていないのですが頑張ってみます
