### ISSUE TITLE
グラフ共有時のタグの追加

### ISSUE THREAD

**Issue by fujiwaraizuho** [stopcovid19-okayama/covid19#54]
## 改善詳細 / Details of Improvement
- 兵庫県の [#188](https://github.com/stop-covid19-hyogo/covid19/issues/188) にならってグラフ共有時のタグの追加
- グラフ共有機能でグラフを共有するとハッシュタグが出ますが、これに岡山県版のタグ(#StopCovid19Okayama と #岡山コロナ情報 )を自動で追加するように修正してください。

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by come25136** [comment]
対応します
