### ISSUE TITLE
メニュータイトルとページタイトルの統一

### ISSUE THREAD

**Issue by come25136** [stopcovid19-okayama/covid19#57]
## 改善詳細 / Details of Improvement
`岡山県内の最新感染動向`となっているのを`県内の最新感染動向`に変更する。

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/12409412/78332505-20f1a000-75c3-11ea-90e2-46886b3549ad.png)

## 期待する見せ方・挙動 / Expected behavior
![image](https://user-images.githubusercontent.com/12409412/78332542-336bd980-75c3-11ea-822c-61e533231fdc.png)

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by manate-anagram** [comment]
SEO的に両方に「岡山」がある方が良いような気がするのですが、いかがでしょうか・・・？
上記で特に意味がない(あるいは悪影響がある)場合、今作業いただいている「岡山」を取ったものの方が冗長でなく良いと思います。

**Comment by come25136** [comment]
https://github.com/stopcovid19-okayama/covid19/blob/d50fffae142071d8f41228cb623f9f3d557b0fc6/nuxt.config.ts#L18
で実装されている通りtitileタグには常に`岡山県`が入るので、SEO的には冗長になるだけだと思います。

**Comment by manate-anagram** [comment]
ご確認ありがとうございます！
了解しました👍
