### ISSUE TITLE
データ更新の半自動化

### ISSUE THREAD

**Issue by y-chan** [stopcovid19-okayama/covid19#60]
## 改善詳細 / Details of Improvement
- いちいちPRしてたら保守性が低下するので、自動化しましょう。
- 情報がリアルタイムに更新されることは重要ですが、それだけでは運用は回りません。
- スクレイピングスクリプトも出来上がっているようですし、データ形式はCSVということでめったに変わらないでしょうから、毎日定時に自動で更新する方式がよいでしょう。

**Comment by y-chan** [comment]
- 私の主にコントリビュートする兵庫県版の話なのであくまで参考程度ですが、スクリプトは1時間毎に実行しておきgh-pagesに公開しておきます。毎日21:15にそこからデータを取得し、自動でPRしています。なので、いつ更新するか時間を決める必要があるでしょう。
- 北海道版のようにデータ更新をAPIに投げるのもありです。バックエンドがさくらの鯖なのであれば、よりアリだと思います。(CORS対策など必要なため)
- そこまで自動化は必要ない、スクリプトを適宜実行して手動PRする、という運用方針で行くならば、このIssueはなんの予告もなしに閉じていただいて構いません。

**Comment by fujiwaraizuho** [comment]
提案ありがとうございます。
半自動化については岡山県の新型コロナウイルス感染症に関するオープンデータを管理している課と調整しつつ進めています。
感染症数や感染者の詳細情報がオープンデータとして公開されておらず、現在公開されているPCR検査人数や相談者数のデータすらまともに更新が追いついていない(数日間更新されない)状況です。
半自動化の実施についてはデータが揃った状態で、かつデータの更新がある程度安定した状態で行いたいと考えています。
このissueに関しては一時保留とさせて頂いても問題ないでしょうか？
半自動化に関する議論の場にしたいと考えています。

**Comment by y-chan** [comment]
> このissueに関しては一時保留とさせて頂いても問題ないでしょうか？
半自動化に関する議論の場にしたいと考えています。

問題ありません。

**Comment by fujiwaraizuho** [comment]
岡山県のご尽力で半自動化に必要なすべての情報が揃いました！
https://github.com/stopcovid19-okayama/covid19-scraping の整備を再開します！

**Comment by fujiwaraizuho** [comment]
データ更新の半自動化を進めていきます！
流れとしては #85 のissueをまずは解決し
data.json の肥大化防止や情報更新のやりやすさを確保します
その後に #60 のissueを進めていきます

**Comment by fujiwaraizuho** [comment]
データ更新の間隔についてと、GitHub Actionの仕様について話し合いたいです

**Comment by y-chan** [comment]
データ更新の間隔は1日に一回、定刻に行うのが適切だと思っています。データがほぼ確実に更新されているだろう、という時間を見計らって定刻を決めるのがよさそうです。

GitHub Actionsの仕様についてというのは？

**Comment by fujiwaraizuho** [comment]
なるほど
その方向で調整します。

GitHub Actionを使って半自動化をすることになると思いますが兵庫と京都に採用されているフローを参考にしようと思っています。
そこでcovid19-scrapingからデータを引っ張ってくる際に update-data-{timestamp} to developmentのPRとは別にdevelopment to masterのPRも同時に発行してしまうのはどうでしょう

**Comment by y-chan** [comment]
問題ないと思います。

**Comment by y-chan** [comment]
GitHub Actionわからんなりに頑張ったので参考までに
これはmasterとdevlopに対して個別にPRを送っているけども、多分似たような形でdevelopからmasterのPRが出来ると思われる

https://github.com/codeforjapan/kobe-stopcovid19/blob/development/.github/workflows/deploy_data.yml

**Comment by fujiwaraizuho** [comment]
確か東京都もその形でしたね
developmentとmasterに個別にPR送った方が保守性高そうだな…

**Comment by y-chan** [comment]
どうでしょ...
毎回conflictが発生することになりそうだけど...

**Comment by fujiwaraizuho** [comment]
たしかに
update-data/master -> master
update-data/development -> development
だとconflict起きますね
なにか対策してるんですか？

**Comment by y-chan** [comment]
私は指示に従って実装しただけなので詳しくは...
データ更新を1日1回にするならdev->masterでも保守性に問題は無いと思うので、その方向で実装した方が良いかと思います。

**Comment by fujiwaraizuho** [comment]
ちょっと思ったんですが
GitHub ActionでPRを発行する際ってその度にそのActionの中でファイルを変更しその差分をPRとして送信してますよね
となると、
update-data/development -> developmentは差分が出てPRは発行できてもdevelopment -> masterはその時点で差分が出ないからPR発行できない気がするんですよね
東京都はどうしてるんだろう…

**Comment by y-chan** [comment]
東京都版では、developで実装した内容はしばらくテストされて本番環境には上がらないのでそういう実装なのかなぁと思ったり

**Comment by fujiwaraizuho** [comment]
まぁとりあえず東京都に準じて実装を進め、運用に問題があればissue上げる感じにしましょう
