### ISSUE TITLE
ソースコードについてのリンクが東京都のものになっている

### ISSUE THREAD

**Issue by fujiwaraizuho** [stopcovid19-okayama/covid19#63]
## 起こっている問題 / The Problem
- ソースコードについてのリンクが東京都のものになっている

## スクリーンショット / Screenshot

![Screenshot from 2020-04-03 23-03-28](https://user-images.githubusercontent.com/30709744/78369015-83689180-75ff-11ea-9a5a-baae20ebc65c.png)

## 期待する見せ方・挙動 / Expected Behavior
- 岡山県のものに変更する

**Comment by manate-anagram** [comment]
対応します！
