### ISSUE TITLE
SNSアカウントリンクの掲載

### ISSUE THREAD

**Issue by fujiwaraizuho** [stopcovid19-okayama/covid19#72]
## 改善詳細 / Details of Improvement
- Twitter(@covid19_okayama)へのリンク掲載
- Facebook(facebook.com/106711727658729)へのリンク掲載

## スクリーンショット / Screenshot

![Screenshot from 2020-04-05 13-56-31](https://user-images.githubusercontent.com/30709744/78467216-460e1c00-7745-11ea-985b-b33e782ffcd5.png)

**Comment by come25136** [comment]
対応します
