### ISSUE TITLE
確保病床や人工呼吸器の数を数字のみで表示する

### ISSUE THREAD

**Issue by fujiwaraizuho** [stopcovid19-okayama/covid19#81]
## 改善詳細 / Details of Improvement
- 岡山県から公開されている確保病床数を数字のみで表示する
- 岡山県から公開されている人工呼吸器の数を数字のみで表示する

https://www.pref.okayama.jp/page/645925.html#kennaijoukyou

**Comment by fujiwaraizuho** [comment]
[TOPページ](https://okayama.stopcovid19.jp)に情報を置くのではなく
別にページを作成してデザインを考え数字のみを並べるのがいいと思います。
皆さんの意見をください

**Comment by nandehu0323** [comment]
# 他県の表現方法
人工呼吸器に関する情報はどのサイトも公開していなかった

## 青森県
円グラフで表示
![image](https://user-images.githubusercontent.com/19589940/79180409-d7b41280-7e44-11ea-9220-9a6e77a5e566.png)
[https://covid19.codeforaomori.org/](https://covid19.codeforaomori.org/)

## 福井県
円グラフで表示
![image](https://user-images.githubusercontent.com/19589940/79182103-edc3d200-7e48-11ea-8875-6c5736348884.png)
[https://covid19-fukui.com/](https://covid19-fukui.com/)

##  兵庫県
> 2020/04/12 病床の大幅追加に伴い、正確な病床数の把握が現時点では困難になったため、「入院患者数と残り病床数」のグラフの公開を一旦中止します。
[https://stop-covid19-hyogo.org/](https://stop-covid19-hyogo.org/)

## 奈良県
円グラフで表示
![image](https://user-images.githubusercontent.com/19589940/79182337-82c6cb00-7e49-11ea-9a0f-887c2474a0b4.png)
[https://stopcovid19.code4nara.org/](https://stopcovid19.code4nara.org/)

## 大分県
円グラフで表示
![image](https://user-images.githubusercontent.com/19589940/79182470-d802dc80-7e49-11ea-852d-9f416497b1b2.png)
[https://oita.stopcovid19.jp/](https://oita.stopcovid19.jp/)

## 沖縄県
画像(PNG)で表示(SVGから画像生成の方法？)
![image](https://user-images.githubusercontent.com/19589940/79182524-f9fc5f00-7e49-11ea-8853-717a9aa1130f.png)
[https://okinawa.stopcovid19.jp/](https://okinawa.stopcovid19.jp/)

**Comment by fujiwaraizuho** [comment]
こんな表現の仕方もあるようです。
数字だけを強調して伝えるには適切なのかな、と
![image](https://user-images.githubusercontent.com/30709744/79199570-24611300-7e70-11ea-9d86-f25f0a3ef6bf.jpeg)

**Comment by fujiwaraizuho** [comment]
滋賀県版にあるSimpleNumberCardですね
https://github.com/Shiga-pref-org/covid19/blob/development/components/SimpleNumberCard.vue

**Comment by fujiwaraizuho** [comment]
SimpleNumberCardを実装する形でとりあえず作ってみます

**Comment by fujiwaraizuho** [comment]
/others っていうページを新設してその他の情報として扱うのはどうだろう
TOPページの情報とはちょっと分けたい

**Comment by come25136** [comment]
良いと思います

**Comment by fujiwaraizuho** [comment]
スケッチ等がない状態だと実装しにくいと思うので明日か明後日に上げますね

**Comment by fujiwaraizuho** [comment]
スケッチ描いてみました！
分かりにくければまた教えてください
![image](https://user-images.githubusercontent.com/30709744/80309181-46fb1080-880e-11ea-8615-cb8dc8e7f805.jpeg)

**Comment by come25136** [comment]
今日から作業始めます

**Comment by come25136** [comment]
PR出してから思いましたが、医療体制整備状況であれば`/others`は相応しくないのではないかと思います

**Comment by fujiwaraizuho** [comment]
確かに、とりあえずDraft Pull Requestにして検討しましょう
/medical とかですかね？

**Comment by come25136** [comment]
`/medical`で良いかと
一応他の人にも聞きたい感じがありますね

**Comment by fujiwaraizuho** [comment]
そうですね

**Comment by manate-anagram** [comment]
内容が医療のことですし、 /medical が適当と思います。

**Comment by Nekoya3** [comment]
https://www.pref.okayama.jp/page/645925.html#kennaijoukyou
データが4/13とまぁまぁ古いデータですが大丈夫ですか...?

**Comment by come25136** [comment]
大丈夫じゃないので県と話してみます( ᐛ )و

**Comment by fujiwaraizuho** [comment]
あれ、データって4月23日更新じゃないです？

**Comment by Nekoya3** [comment]
新しくなってますね…よかった

**Comment by come25136** [comment]
#182 `/others`から`/medical`に変更とデータ更新しました

**Comment by y-chan** [comment]
@come25136 
> #182 /othersから/medicalに変更とデータ更新しました

PR見ますと、nuxt.config.tsのrouteしかmedicalに変わってないように見えます。
pages下のothers.vueのファイル名と、その中の上層のdivのクラス名もMedicalに変えないと意味がないですね...

**Comment by come25136** [comment]
直しました
